# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [12]:
import numpy as np

print(np.zeros((5, 5)))
print(np.empty((22, 22))) #不會初始化陣列內元素初始值 內容為不確定的

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 1.46005862e-311  1.46005559e-311  1.46011145e-311  1.46004707e-311
   1.97626258e-323  0.00000000e+000              nan  2.22329541e-322
   6.37173391e-154  0.00000000e+000  3.95252517e-323  1.46011145e-311
   1.46004707e-311  9.88131292e-324  0.00000000e+000              nan
   2.22329541e-322  1.45993310e-311  3.55727265e-322  3.95252517e-323
   1.46011145e-311  1.46004707e-311]
 [ 9.88131292e-324  0.00000000e+000              nan  4.15015143e-322
   1.45993310e-311  7.11454530e-322  3.95252517e-323  1.46011145e-311
   1.46004707e-311  9.88131292e-324  0.00000000e+000              nan
   2.86558075e-322  1.45993310e-311  1.06718180e-321  3.95252517e-323
   1.46011145e-311  1.46004707e-311  9.88131292e-324  0.00000000e+000
               nan  2.86558075e-322]
 [ 1.45993310e-311  1.42290906e-321  3.95252517e-323  1.46011145e-311
   1.46004707e-311  9.88131292e-324  0.00000000e+000             

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [22]:
# 記得先 Import 正確的套件

import numpy as np
from numpy.random import default_rng
rng = default_rng()

In [23]:
# 參考解答

a = np.random.rand(2, 3)

print(a)
print(a.round())

[[0.96461451 0.33856309 0.54587848]
 [0.56607425 0.92338413 0.48297817]]
[[1. 0. 1.]
 [1. 1. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [26]:
m = 20
n = 40

# normal = rng.standard_normal((3,2)) 
# random = rng.random((3,2))
integers = rng.integers(m, n, size=(3,2))
print(integers)

[[36 27]
 [25 31]
 [38 25]]
