# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [2]:
import numpy as np
a = np.array([1, 2, 3])
print(a.sum()) 
print(np.sum(a))
print(sum(a))

6
6
6


In [5]:
b = [1, 2, 3]
print(b.sum()) 
print(np.sum(b))
print(sum(b))
#List無法使用sum屬性 只能使用numpy和python函數

AttributeError: 'list' object has no attribute 'sum'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [6]:
# 記得先 Import 正確的套件
import numpy as np

In [17]:
A = np.random.random((5, 5))
print(A)

range_ = np.max(A) - np.min(A)
B = (A - np.min(A)) / range_
print(B)

[[0.5555329  0.71987589 0.9267407  0.73326204 0.69228869]
 [0.92587253 0.90949741 0.13940394 0.74579103 0.88786168]
 [0.13247551 0.43521614 0.52382574 0.3324619  0.85671284]
 [0.75978436 0.09003176 0.91388864 0.65367214 0.10196203]
 [0.25496879 0.83104043 0.99201471 0.1866801  0.68139665]]
[[0.5160864  0.69828829 0.92763276 0.71312909 0.66770323]
 [0.92667025 0.90851567 0.05473737 0.72701958 0.88452883]
 [0.04705604 0.38269501 0.48093368 0.26877463 0.84999509]
 [0.74253354 0.         0.9133841  0.62489028 0.01322671]
 [0.18286048 0.8215329  1.         0.10715096 0.65562757]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [24]:
C = np.random.random(10)
print(C)

result = []
for i in C:
    if i == C.max():
        i = -1
        result.append(i)
    else:
        result.append(i)
print(result)

[0.59150562 0.72608773 0.38108031 0.73023524 0.41923601 0.30078435
 0.99582274 0.13776386 0.96411579 0.18003809]
[0.5915056225307165, 0.7260877325999743, 0.38108030550017713, 0.7302352358810048, 0.41923600918520376, 0.30078435087390243, -1, 0.13776385819097414, 0.9641157890211738, 0.18003809376449842]
